# Generated by Django 3.1.3 on 2021-01-04 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_games'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='game_image',
            new_name='aminaries_image',
        ),
        migrations.RenameField(
            model_name='games',
            old_name='game_no',
            new_name='aminaries_no',
        ),
        migrations.RenameField(
            model_name='games',
            old_name='game_type',
            new_name='aminaries_type',
        ),
    ]
