# Generated by Django 3.1.3 on 2021-01-04 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200314_1916'),
        ('booking', '0010_auto_20210104_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gbooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.DateField()),
                ('end_day', models.DateField()),
                ('amount', models.FloatField()),
                ('booked_on', models.DateTimeField(auto_now=True)),
                ('aminaries_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.rooms')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.customer')),
            ],
        ),
    ]
