# Generated by Django 3.1.3 on 2021-01-06 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_fbooking_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gbooking',
            name='aminaries_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.games'),
        ),
    ]
