# Generated by Django 3.1.3 on 2021-01-06 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20210106_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbooking',
            name='food_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.food'),
        ),
    ]
