# Generated by Django 3.1.3 on 2021-01-06 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20210106_1243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fbooking',
        ),
    ]
